# Generated by Django 5.1.4 on 2024-12-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0002_remove_movieslot_unique_slot_time_per_screen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='seat_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
