# Generated by Django 5.1.4 on 2024-12-16 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0003_alter_screen_seat_capacity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('theatre', 'name')},
        ),
    ]
